Repository facebookresearch/labgraph, pull requests merged in 2021-12, with the labels that each got.

#26 LSL Implementation
  labgraph/devices/protocols/lsl/__init__.py
  labgraph/devices/protocols/lsl/lsl_message.py
  labgraph/devices/protocols/lsl/lsl_poller_node.py
  labgraph/devices/protocols/lsl/lsl_sender_node.py
  labgraph/devices/protocols/lsl/tests/__init__.py
  labgraph/devices/protocols/lsl/tests/test_lsl_node.py
  setup.py
  test_script.sh
Labels: enhancement, CLA Signed

#28 bennaaym/yaml_support : lg_units to YAML parser
  .github/workflows/extensions.yml
  extensions/yaml_support/setup.py
  extensions/yaml_support/yaml_support/README.md
  extensions/yaml_support/yaml_support/__init__.py
  extensions/yaml_support/yaml_support/_parser/base_parser.py
  extensions/yaml_support/yaml_support/_parser/lg_units_parser.py
  extensions/yaml_support/yaml_support/enums/lg_units_enum.py
  extensions/yaml_support/yaml_support/loader/base_loader.py
  extensions/yaml_support/yaml_support/loader/errors/errors.py
  extensions/yaml_support/yaml_support/loader/python_file_loader.py
  extensions/yaml_support/yaml_support/main.py
  extensions/yaml_support/yaml_support/model/base_model.py
  extensions/yaml_support/yaml_support/model/lg_unit_model.py
  extensions/yaml_support/yaml_support/serializer/base_serializer.py
  extensions/yaml_support/yaml_support/serializer/yaml_serializer.py
  extensions/yaml_support/yaml_support/tests/test_lg_yaml_api.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_config.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_graph.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_group.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_message.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_node.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_lg_unit_state.py
  extensions/yaml_support/yaml_support/tests/tests_code/test_py_code.py
  extensions/yaml_support/yaml_support/yamlify.py
Labels: CLA Signed

#35 Add a labgraph_protocol extension for experiments
  extensions/labgraph_protocol/MANIFEST.in
  extensions/labgraph_protocol/README.md
  extensions/labgraph_protocol/labgraph_protocol/__init__.py
  extensions/labgraph_protocol/labgraph_protocol/examples/__init__.py
  extensions/labgraph_protocol/labgraph_protocol/examples/__main__.py
  extensions/labgraph_protocol/labgraph_protocol/examples/audio_player.mp3
  extensions/labgraph_protocol/labgraph_protocol/examples/audio_player.py
  extensions/labgraph_protocol/labgraph_protocol/examples/display_image.jpg
  extensions/labgraph_protocol/labgraph_protocol/examples/display_image.py
  extensions/labgraph_protocol/labgraph_protocol/examples/labels_buttons.py
  extensions/labgraph_protocol/labgraph_protocol/examples/random_targets.py
  extensions/labgraph_protocol/labgraph_protocol/examples/text_box_w_feedback.py
  extensions/labgraph_protocol/labgraph_protocol/examples/video_player.mp4
  extensions/labgraph_protocol/labgraph_protocol/examples/video_player.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/__init__.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/audio_player.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/button_w_callback.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/common.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/image_widget.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/label_widget.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/mouse_target.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/text_box_w_result.py
  extensions/labgraph_protocol/labgraph_protocol/helpers/video_player.py
  extensions/labgraph_protocol/labgraph_protocol/priority_queue.py
  extensions/labgraph_protocol/labgraph_protocol/protocol.py
  extensions/labgraph_protocol/labgraph_protocol/protocol_node.py
  extensions/labgraph_protocol/labgraph_protocol/qt_node.py
  extensions/labgraph_protocol/labgraph_protocol/qt_stimulus.py
  extensions/labgraph_protocol/labgraph_protocol/qt_widgets.py
  extensions/labgraph_protocol/labgraph_protocol/stimulus.py
  extensions/labgraph_protocol/setup.py
Labels: CLA Signed

#36 [labgraph_protocol] Add option for fullscreen; Fix examples
  extensions/labgraph_protocol/labgraph_protocol/examples/__main__.py
  extensions/labgraph_protocol/labgraph_protocol/qt_node.py
  extensions/labgraph_protocol/labgraph_protocol/qt_widgets.py
Labels: CLA Signed

#23 Flake support
  docs/tools/codetools/.flake8
  docs/tools/codetools/README.md
Labels: documentation, CLA Signed

#32 Add python executable back to config_var.
  third-party/python/DEFS
Labels: CLA Signed
